
name: PokerApp
options:
  bundleIdPrefix: com.example
targets:
  PokerApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [PokerApp]
    settings:
      base:
        PRODUCT_NAME: PokerApp
        SWIFT_VERSION: 5.0
        INFOPLIST_FILE: PokerApp/Info.plist
        INFOPLIST_KEY_CFBundleVersion: 1
        INFOPLIST_KEY_CFBundleShortVersionString: 1.0
        INFOPLIST_KEY_CFBundleExecutable: $(PRODUCT_NAME)
        INFOPLIST_KEY_CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
